---
title: "Fragile Families Challenge"
author: "Myeong Lee, Joanna Pepin, Andrew Wolf, Elliot Stoller ,Danya Lagos"
date: "6/22/2018"
output: html_document
---


```{r, echo=FALSE}
library(maps)
library(geosphere)
library(readr)
library(dplyr)
library(magrittr)
library(lubridate)
library(rgdal)
library(raster)
library(rgeos)
require(ggplot2)
library(cwhmisc)
library(utils)
library(rpart)
library(stringr)
library(hydroGOF)
library(fields)
library(MASS)
library(e1071)
library(raster)
library(reshape2)
library(igraph)
library(randomForest)
```

```{r}
setwd('/Users/myeong/git/SICSS_NYU/FFChallenge_v5/')

# background <- read_delim("background.csv", delim = ",",col_names = TRUE ) 
# ref <- read_delim("train.csv", delim = ",",col_names = TRUE )
metadata <- read_delim("FFMetadata20180221.csv", delim = ",",col_names = TRUE ) 
train <- read_delim("dfmeans.csv", delim = ",",col_names = TRUE ) # Imputed data
train <- train[,-1]
not.mis <- rowSums(is.na(train))==0
train <- train[not.mis,]

predict <- read_delim("df2means.csv", delim = ",",col_names = TRUE ) # Imputed data
predict <- predict[,-1]

final <- read_delim("prediction_ori.csv", delim = ",",col_names = TRUE ) 

# train[,names(train) %in% c("gpa","grit","materialHardship", "eviction", "eviction", "layoff", "jobTraining")==F] <- apply(train[,names(train) %in% c("gpa","grit","materialHardship", "eviction", "eviction", "layoff", "jobTraining")==F], 2, function(x) as.factor(x))

# train <- train %>% left_join(background, by=c("challengeID")) 
# remove (background)

# Creating formula to include every 

train$gpa <- as.factor(train$gpa)
predict$gpa <- as.factor(predict$gpa)
train$grit <- as.factor(train$grit)
predict$grit <- as.factor(predict$grit)
train$materialHardship <- as.factor(train$materialHardship)
predict$materialHardship <- as.factor(predict$materialHardship)
train$eviction <- as.factor(train$eviction)
predict$eviction <- as.factor(predict$eviction)
train$layoff <- as.factor(train$layoff)
predict$layoff <- as.factor(predict$layoff)
train$jobTraining <- as.factor(train$jobTraining)
predict$jobTraining <- as.factor(predict$jobTraining)

# Prediction file
not.mis <- rowSums(is.na(predict))==0
predict <- predict[not.mis,]

# final
final <- final[1:length(pred), ]
final$challengeID <- predict$challengeID

run <- function (variable){
  lhs<- variable
  operator<-" ~ "
  rhs<-paste0(  names(train[,2:70]),   collapse=" + ") 
  thisform<-paste0(
    lhs,
    operator,
    rhs
  ) %>% as.formula
  
  # just for submission
  # model <- svm (thisform, data=train)
  model <- randomForest (thisform, data=train, ntree=100, importance=TRUE, proximity=TRUE, na.action=na.omit)
  pred <- predict(model, predict)

  return (pred)


}

final$gpa <- run ("gpa")
final$grit <-run ("grit")
final$materialHardship <-run ("materialHardship")
final$eviction <-run ("eviction")
final$layoff <-run ("layoff")
final$jobTraining <-run ("jobTraining")

write.table(final, paste0("rf_NYU_team1_predict.csv"), row.names=F, col.names=T, sep=",")

# tb <- table(pred = pred, true= testset$gpa )















proportions <- seq(80, 90, 10)

rand_error_table <- matrix(NA,nrow=length(proportions),ncol=3)
colnames(rand_error_table) <- c("train", "score", "error")
num_test <- 1


calculate_svm_table <- function (variable){
  
  for (i in 1:length(proportions) ){
    print (proportions[i])
    
    temp_table <- data.frame(nrow=num_test, ncol=2)
    colnames(temp_table) <- c("score", "error")
    
    for (j in 1:num_test){
      index <- 1:nrow(train)
      testindex <- sample(index, trunc(length(index) * (100-proportions[i]) / 100 ))
      testset <- train[testindex,]      
      trainset <- train[-testindex,]
            
      if (variable == "random"){   
        rand1 <- rnorm (5000, mean(train$gpa, na.rm=TRUE), sd(train$gpa, na.rm=TRUE))
        rand2 <- rnorm (5000, mean(train$gpa, na.rm=TRUE), sd(train$gpa, na.rm=TRUE))
        rand <- c(rand1, rand2)        
        trainset$rand_base <- sample(rand, length(trainset$gpa), replace = FALSE, prob = NULL)     
        # model <- svm (thisform, data=trainset)
        model <- svm (gpa ~ rand_base, data=trainset)
        testset$rand_base <- sample(rand, length(testset$gpa), replace = FALSE, prob = NULL)     
        
      } else if (variable == "test"){
        model <- svm (thisform, data=trainset)
        testset <- testset[!is.na(testset$cf1intyr),]
      }
      
      pred <- predict(model, testset)
      tb <- table(pred = pred, true= testset$gpa )
            
      temp_table[j,] <- c(classAgreement(tb)$diag, 1-sum(diag(tb))/sum(tb))
    }
    temp_table <- apply(temp_table, 2, mean)    
    
    rand_error_table[i,] <- c(proportions[i], temp_table["score"], temp_table["error"])
  }
  rand_error_table <- as.data.frame(rand_error_table)
  return (rand_error_table)
}

rand <- calculate_svm_table ("random")
past <- calculate_svm_table ("test")


# Baseline Graph Drawing
draw_graph_base <- function (column){
  dd <- cbind(rand$train, rand[,column], past[,column] )
  colnames(dd) <- c("train","random", "density")

  dd <- as.data.frame(dd)
  df <- melt(dd, id.vars='train')
  colindex <- round(as.integer(as.factor(df$variable) ))
  
  ggplot(df, aes(x = train, y = value, shape=factor(variable), colour=factor(variable))) +
    geom_point(size = 3) +
    geom_line() +
    scale_x_continuous('Train Proportion (%)',limits=c(50,100)) + 
#     scale_y_continuous('Rho',limits=c(0.95, 1.05)) +
    theme_bw() + 
    geom_hline(yintercept=0) + theme(legend.text=element_text(size=15))
}

draw_graph_base("score")
draw_graph_base("error")









```

#post processing

```{r}
ori <- read_delim("prediction_ori.csv", delim = ",",col_names = TRUE ) 
'%!in%' <- function(x,y)!('%in%'(x,y))

ids_missing <- ori[(ori$challengeID %!in%  final$challengeID)==T,]$challengeID
empty <- data.frame(matrix(ncol=7, nrow=length(ids_missing)))

svm <- read_delim("svm.csv", delim = ",",col_names = TRUE ) 
colnames(empty) <- colnames(svm)
empty$challengeID <- ids_missing
svm <- rbind(svm, empty)
write.table(svm, paste0("svm.csv"), row.names=F, col.names=T, sep=",")


rf <- read_delim("rf.csv", delim = ",",col_names = TRUE ) 
rf <- rbind(rf, empty)
write.table(rf, paste0("rf.csv"), row.names=F, col.names=T, sep=",")

svm <- read_delim("svm.csv", delim = ",",col_names = TRUE ) 
svm[is.na(svm)] <-0
write.table(svm, paste0("svm.csv"), row.names=F, col.names=T, sep=",")

rf <- read_delim("rf.csv", delim = ",",col_names = TRUE ) 
rf[is.na(rf)] <-0
write.table(rf, paste0("rf.csv"), row.names=F, col.names=T, sep=",")

```

